services:
  duplicati:
    image: duplicati/duplicati:2.1.2.0
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    restart: unless-stopped
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - FOWNER
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    ports:
      - "8200:8200/tcp"
    environment:
      TZ: "${TZ}"
      DUPLICATI__DISABLE_DB_ENCRYPTION: "true"
      DUPLICATI__WEBSERVICE_PASSWORD: "${DUPLICATI_ADMIN_PASS}"
    networks:
      - duplicati
    volumes:
      - /opt/docker/duplicati/duplicati_data:/data
      - /Data/IT/Backups:/backups
      - /opt/docker:/source:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  duplicati:
    external: false
    name: "duplicati"
    driver: bridge
