x-versions:
  loki: &loki-version "grafana/loki:3.6.3"
  promtail: &promtail-version "grafana/promtail:3.6.3"

services:
  loki:
    container_name: loki
    image: *loki-version
    restart: unless-stopped
    user: ${DOCKER_PUID}:${DOCKER_PGID}
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    command: ["-config.file=/etc/loki/local-config.yml"]
    environment:
      TZ: "${TZ}"
    hostname: loki
    ipc: private
    networks:
      - monitoring
    ports: []  # Grafana talks to http://loki:3100 inside the network
    volumes:
      - /opt/docker/loki-promtail/loki-config.yml:/etc/loki/local-config.yml:ro
      - /opt/docker/loki-promtail/loki_storage:/loki
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/3100 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    labels:
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.display.name: "Loki"
      wud.display.icon: "si:grafana"
      wud.link.template: 'https://github.com/grafana/loki/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    container_name: promtail
    image: *promtail-version
    restart: unless-stopped
    user: ${DOCKER_PUID}:${DOCKER_PGID}
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    command: ["-config.file=/etc/promtail/config.yml"]
    environment:
      TZ: "${TZ}"
    hostname: promtail
    ipc: private
    networks:
      - monitoring
    volumes:
      - /opt/docker/loki-promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    depends_on:
#      loki:
#        condition: service_healthy
#        restart: true
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/9080 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s
    labels:
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.display.name: "Promtail"
      wud.display.icon: "si:grafana"
      wud.link.template: 'https://github.com/grafana/loki/releases/tag/v$${major}.$${minor}.$${patch}'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  monitoring:
    name: monitoring
    driver: bridge
    external: true
