services:
  boinc:
    image: lscr.io/linuxserver/boinc:8.2.5
    container_name: boinc
    ipc: private
    security_opt:
      - seccomp:unconfined #optional
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    environment:
      PUID: "${DOCKER_PUID}"
      PGID: "${DOCKER_PGID}"
      TZ: "${TZ}"
      PASSWORD: #optional
    volumes:
      - /opt/docker/boinc/boinc_config:/config
    ports:
      - 8080:8080
    resources:
      limits:
        cpus: "2"
        memory: 1024M
      reservations:
        memory: 128M
    restart: unless-stopped
    networks:
      - boinc
networks:
  boinc:
    driver: bridge
    name: boinc
    external: false