x-versions:
  vdirsyncer-version: &vdirsyncer-version bleala/vdirsyncer:latest

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-vdirsyncer-env: &vdirsyncer-env
  TZ: ${TZ:-UTC}

services:
  vdirsyncer:
    image: *vdirsyncer-version
    container_name: vdirsyncer
    ipc: private
    restart: unless-stopped
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    security_opt: ["no-new-privileges:true"]
    cap_drop: [ALL]
    mem_limit: 256M
    environment:
      <<: *vdirsyncer-env
      AUTODISCOVER: "false"
      AUTOSYNC: "true"
      CRON_TIME: "${VDIRSYNCER_CRON_TIME:-*/15 * * * *}"
    volumes:
      - /opt/docker/vdirsyncer/vdirsyncer_config/config:/vdirsyncer/config:ro
      - /opt/docker/vdirsyncer/vdirsyncer_status:/status
      - /opt/docker/vdirsyncer/vdirsyncer_tokens:/vdirsyncer/tokens
      - /etc/localtime:/etc/localtime:ro
    networks: [vdirsyncer]
    logging: *default-logging
    labels:
      wud.watch: "true"
      wud.tag.include: '^latest$$'
      wud.link.template: "https://github.com/bleala/vdirsyncer-docker/releases"
      wud.display.name: "vdirsyncer"

networks:
  vdirsyncer:
    name: vdirsyncer
    driver: bridge