services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2025.5.2
    ipc: private
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - DAC_OVERRIDE 
      - DAC_READ_SEARCH
      - CHOWN
      - FOWNER
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    restart: unless-stopped
    networks:
      - esphome
    volumes:
      - /opt/docker/esphome/config:/config:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    environment:
      TZ: "${TZ}"
    labels:
      wud.watch: "true"
      wud.tag.include: '^\d+\.\d+\.\d+$$'
      wud.link.template: 'https://github.com/esphome/esphome/releases/tag/v$${major}.$${minor}.$${patch}'
      wud.display.name: 'ESPHome'
      wud.display.icon: 'sh:esphome'
      repliqate.enabled: 'true'
      repliqate.schedule: "@weekly 3am"
      repliqate.backup_id: esphome
      repliqate.retention: "90d"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: >
        wget -q -T2 -O- http://localhost:6052/ | grep "ESPHome Dashboard" || exit 1

networks:
  esphome:
    driver: bridge
    external: false
    name: esphome
