services:
  harborguard:
    image: ghcr.io/harborguard/harborguard:latest
    ipc: private
    depends_on:
      harborguard-postgres:
        condition: service_healthy
    labels:
      wud.display.name: "HarbourGuard"
      wud.display.icon: "sh-harbourguard" #no icon yet
      wud.digest: "true"
      wud.watch: "true"
    environment:
      MAX_CONCURRENT_SCANS: "5"
      PORT: "3005"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"  
    ports:
      - "3005:3005"
    networks:
      - harborguard
  harborguard-postgres:
    image: postgres:16.10-alpine
    container_name: harborguard-postgres
    ipc: private
    cap_add:
      - CHOWN
      - FOWNER
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    labels:
      wud.watch: "true"
      wud.tag.include: '^16\.\d+-alpine$$'
      wud.link.template: 'https://github.com/postgres/postgres/releases/tag/REL_$${major}_$${minor}'
      wud.display.name: "Harborguard - Postgres"
      wud.display.icon: "sh-harborguard"  
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 50m
    environment:
      POSTGRES_DB: "harborguard"
      POSTGRES_USER: "harborguard"
      POSTGRES_PASSWORD: "${HARBORGUARD_DB_PASS}"
    volumes:
      - /opt/docker/harborguard/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - harborguard
      - adminer

networks: 
  harborguard:
    external: false
    name: harborguard
    driver: bridge
  adminer:
    external: true